name: Build Docker Image

on:
  push:
    branches:
      - master  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
        docker buildx build --file Dockerfile --tag vinukarthek/resume:${{ github.sha }} .
        docker push vinukarthek/resume:${{ github.sha }}
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
